# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-24 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pwd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='vcms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('server', models.CharField(max_length=200)),
                ('busy', models.CharField(max_length=200)),
            ],
        ),
    ]
