# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_servers'),
    ]

    operations = [
        migrations.CreateModel(
            name='kmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(default='', max_length=200)),
                ('sys', models.CharField(default='', max_length=200)),
                ('cpu', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('nance', models.IntegerField(default=0)),
                ('lastreport', models.DateTimeField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='servers',
            name='availableInst',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='servers',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servers',
            name='lastreport',
            field=models.DateTimeField(default=0),
        ),
        migrations.AddField(
            model_name='servers',
            name='mem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servers',
            name='nance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servers',
            name='spec',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='servers',
            name='sys',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servers',
            name='totalInst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servers',
            name='ip',
            field=models.CharField(default='', max_length=200),
        ),
    ]
