# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20181116_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmc',
            name='lastreport',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='servers',
            name='lastreport',
            field=models.DateTimeField(default=''),
        ),
    ]
